spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/mreal
#    url: jdbc:mysql://some_mysql:3306/mreal
#    url: jdbc:mysql://localhost:3306/mreal
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 1Mb
      max-request-size: 10Mb


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  routeAuthenticationPath: /auth
  routeAuthenticationRefresh: /refresh

server:
  port: 9090




